name: Deploy Stream Tracker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './stream-tracker/package.json'
    
    - name: Install dependencies
      working-directory: ./stream-tracker
      run: npm ci
    
    - name: Build
      working-directory: ./stream-tracker
      run: |
        npm run build --if-present
    
    - name: Test
      working-directory: ./stream-tracker
      run: npm test 